from __future__ import annotations

import json
import logging
import smtplib
import sqlite3
from datetime import datetime, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from jinja2 import Template

from iu.config import AppConfig
from iu.db import get_items_by_date, get_active_persons, get_active_products, get_latest_report

logger = logging.getLogger(__name__)

EMAIL_TEMPLATE = """<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
body { font-family: -apple-system, sans-serif; color: #333; max-width: 700px; margin: 0 auto; padding: 20px; }
h1 { color: #1a1a2e; font-size: 20px; border-bottom: 2px solid #1a1a2e; padding-bottom: 8px; }
h2 { color: #333; font-size: 16px; margin-top: 24px; }
.item { background: #f9f9f9; padding: 12px; margin: 8px 0; border-radius: 6px; border-left: 3px solid #1a1a2e; }
.item .source { font-size: 11px; color: #999; text-transform: uppercase; }
.item .title { font-weight: 600; margin: 4px 0; }
.item .content { font-size: 13px; color: #666; }
.item a { color: #1565c0; }
.footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #eee; font-size: 12px; color: #999; }
</style></head>
<body>
<h1>AI Intelligence Report — {{ week_start }}</h1>
<p>Total items: {{ total }}</p>

{% for person_name, person_items in persons.items() %}
<h2>{{ person_name }} ({{ person_items|length }})</h2>
{% for item in person_items %}
<div class="item">
    <div class="source">{{ item.source }}</div>
    <div class="title"><a href="{{ item.source_url }}">{{ item.title or '(no title)' }}</a></div>
    <div class="content">{{ (item.content or '')[:200] }}</div>
</div>
{% endfor %}
{% endfor %}

{% for product_name, product_items in products.items() %}
<h2>{{ product_name }} ({{ product_items|length }})</h2>
{% for item in product_items %}
<div class="item">
    <div class="source">{{ item.source }}</div>
    <div class="title"><a href="{{ item.source_url }}">{{ item.title or '(no title)' }}</a></div>
    <div class="content">{{ (item.content or '')[:200] }}</div>
</div>
{% endfor %}
{% endfor %}

{% if unlinked %}
<h2>Other News ({{ unlinked|length }})</h2>
{% for item in unlinked %}
<div class="item">
    <div class="source">{{ item.source }}</div>
    <div class="title"><a href="{{ item.source_url }}">{{ item.title or '(no title)' }}</a></div>
    <div class="content">{{ (item.content or '')[:150] }}</div>
</div>
{% endfor %}
{% endif %}

<div class="footer">
    Generated by Information Union · {{ generated_at }}
</div>
</body></html>"""


async def send_report(conn: sqlite3.Connection, config: AppConfig) -> None:
    """Send the latest report via email."""
    if not config.email.enabled:
        logger.info("Email is disabled in config.")
        return

    # Get this week's data
    today = datetime.utcnow()
    week_start = today - timedelta(days=today.weekday())
    week_end = week_start + timedelta(days=6)

    start_str = week_start.strftime("%Y-%m-%d")
    end_str = week_end.strftime("%Y-%m-%dT23:59:59")

    items = get_items_by_date(conn, start_str, end_str)
    if not items:
        logger.info("No items to report.")
        return

    # Group items
    persons_map = {p["id"]: p["name"] for p in get_active_persons(conn)}
    products_map = {p["id"]: p["name"] for p in get_active_products(conn)}

    by_person: dict[str, list] = {}
    by_product: dict[str, list] = {}
    unlinked: list = []

    for item in items:
        pid = item.get("person_id")
        prid = item.get("product_id")
        if pid and pid in persons_map:
            by_person.setdefault(persons_map[pid], []).append(item)
        elif prid and prid in products_map:
            by_product.setdefault(products_map[prid], []).append(item)
        else:
            unlinked.append(item)

    # Render email
    html = Template(EMAIL_TEMPLATE).render(
        week_start=start_str,
        total=len(items),
        persons=by_person,
        products=by_product,
        unlinked=unlinked,
        generated_at=datetime.utcnow().isoformat(),
    )

    # Send
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"AI Intelligence Report — {start_str}"
    msg["From"] = config.email.from_addr
    msg["To"] = ", ".join(config.email.to_addrs)
    msg.attach(MIMEText(html, "html"))

    try:
        if config.email.smtp_port == 465:
            # SSL (163, QQ, etc.)
            with smtplib.SMTP_SSL(config.email.smtp_host, config.email.smtp_port) as server:
                server.login(config.email.smtp_user, config.email.smtp_password)
                server.send_message(msg)
        else:
            # STARTTLS (Gmail 587, etc.)
            with smtplib.SMTP(config.email.smtp_host, config.email.smtp_port) as server:
                server.starttls()
                server.login(config.email.smtp_user, config.email.smtp_password)
                server.send_message(msg)
        logger.info(f"Email sent to {config.email.to_addrs}")
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        raise
